name: 'telegram_dbt'
version: '1.0'
config-version: 2

profile: 'telegram_dbt'

model-paths: ['models']
target-path: 'target'
clean-targets: ['target', 'dbt_modules']

models:
  telegram_dbt:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table

