name: 'telegram_dbt'
version: '1.0.0'
config-version: 2
profile: 'telegram_dbt'
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
docs-paths: ["docs"]

models:
  telegram_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table