telegram_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      port: "{{ env_var('DB_PORT', '5432') }}"
      dbname: "{{ env_var('DB_NAME', 'telegram_db') }}"
      user: "{{ env_var('DB_USER', 'postgres') }}"
      pass: "{{ env_var('DB_PASSWORD') }}"
      schema: dbt_telegram