version: 2

models:
  - name: stg_telegram_messages
    description: "Cleaned and standardized raw messages from Telegram."
    columns:
      - name: message_id
        tests: [not_null, unique]
      - name: message_date
        tests: [not_null]
      - name: channel_name
        tests: [not_null]

  - name: dim_channels
    description: "Dimension table for distinct Telegram channels."
    columns:
      - name: channel_id
        tests: [not_null, unique]

  - name: dim_dates
    description: "Dimension table for message dates (year, month, day)."
    columns:
      - name: date_id
        tests: [not_null, unique]

  - name: fct_messages
    description: "Fact table linking messages to dates and channels with metrics."
    columns:
      - name: message_id
        tests: [not_null]
      - name: message_date
        tests: [not_null]
      - name: has_image

  - name: fct_image_detections
    description: YOLO-based image object detection results linked with telegram messages
    columns:
      - name: message_id
        description: Unique Telegram message ID
      - name: channel
        description: Telegram channel name
      - name: detected_class
        description: Object class detected in image
      - name: detection_confidence
        description: Confidence score of YOLO detection
      - name: date
        description: When the message was posted
      - name: text
        description: Telegram message text
      - name: file_path
        description: Local image file path
